version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "./wait-for-it.sh db:5432 -- npm start" # Wait for the db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  data:
